### ISSUE TITLE
[Bug]: Ambiguous class error on composer install 

### ISSUE THREAD

**Issue by raf-lv** [spatie/error-solutions#3]
### What happened?

got dozens of errors similar to this below while running `composer install`

`Warning: Ambiguous class resolution, "Spatie\LaravelIgnition\Solutions\SuggestCorrectVariableNameSolution" was found in both "<project folder>/vendor/spatie/error-solutions/legacy/laravel-ignition/Solutions/SuggestCorrectVariableNameSolution.php" and "<project folder>/vendor/spatie/laravel-ignition/src/Solutions/SuggestCorrectVariableNameSolution.php", the first will be used
`

here's my composer require:

```
  "require": {
    "php": "^8.2",
    "fruitcake/laravel-cors": "^2.0",
    "guzzlehttp/guzzle": "^7.0.1",
    "laravel/framework": "^9.0",
    "laravel/sanctum": "^2.10",
    "laravel/tinker": "^2.5",
    "laravel/ui": "^3.2",
    "predis/predis": "^2.1",
    "pusher/pusher-php-server": "~6.1",
    "rebing/graphql-laravel": "^8.3",
    "sentry/sentry-laravel": "^4.6",
    "silber/bouncer": "^1.0",
    "spatie/laravel-http-logger": "^1.7"
  },
  "require-dev": {
    "alefesouza/laravel-vue-i18n-generator": "^0.2",
    "barryvdh/laravel-ide-helper": "^2.12",
    "fakerphp/faker": "^1.9.1",
    "laravel/sail": "^1.0.1",
    "mockery/mockery": "^1.4.2",
    "nunomaduro/collision": "^6.1",
    "phpunit/phpunit": "^9.3.3",
    "spatie/laravel-ignition": "1.0"
  },

```

### How to reproduce the bug

run composer install 

### Package Version

1.0

### PHP Version

8.2.20

**Comment by rubenvanassche** [comment]
These are not errors but warning telling you that you've got two versions of a class within your vendor. This is because we extracted the solutions for ignition to this package to make them easier to use. Making sure you've got the latest version of Ignition should make the warnings disappear.
